### PR TITLE
composer: drop duplicated information

### PR DESCRIPTION
**Pull request by TomasVotruba**
`^2.3` already allows _2.4_. It stands for: >=2.3,<3

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you

**Comment by paveljanda** [comment]
God damn. I meant `~`. Once `^` was in clipboard, somebody forgot to think..

**Comment by TomasVotruba** [comment]
In this case it's doesn't matter.

~2.3 == ^2.3

It makes difference for **patch version**: ^2.3**.0** != ~2.3**.0**: 

See this answer: http://stackoverflow.com/a/22345808/1348344

**Comment by paveljanda** [comment]
I think it does matter. If Nette 2.5 is released, ublaboo packages would accept that version. But that would be wrong. Ublaboo packages are tested on Nette 2.3.x and 2.4.x.

`^2.3` == [`2.3.1`, `2.4.2`, `2.5.3`] == wrong
`~2.3|~2.4` == [`2.3.1`, `2.4.2`]

I think i will change all packages again to match all nette packages at version `~2.3|~2.4`.

**Comment by TomasVotruba** [comment]
Both `~2.3` and `^2.4` allows >=2.3, <3, see the answer.

If you want to disallow 2.5, `~2.3,<2.5` should do the trick. Yet I would not recommend that.

**Pull request merged**
